### ISSUE TITLE
Add document type "data"

### ISSUE THREAD

**Issue by stefanocoretta** [glottolog/glottolog#1047]
Hi! I wonder if a new document type for datasets/data/raw data and the like can be added (I'm thinking specially audio/video recordings/ specialised data (like egg, ultrasound, behavioural), tabular data, images, maps etc).

I see there several entries that seem to be data of that sort but have no document type specified.

Having a document type like "data" would help researchers finding data that could be used for further processing/investigations.

**Comment by d97hah** [comment]
Can you give examples of such entries?

Pada Jum, 22 Des 2023 pukul 16.48 Stefano Coretta ***@***.***>
menulis:

**Comment by stefanocoretta** [comment]
Sure! For example:

> Alfarano, Valentina. 2018. Documenting Nalögo, an Oceanic language of Santa Cruz Island. Endangered Languages Archive. Handle: http://hdl.handle.net/2196/00-0000-0000-0010-7A76-9

I see that the references contain Valentina's dissertation but it would be good to also have the bib entry for the data archive, which wouldn't have a dedicated document type available.

Or another more field specific example:

Coretta, Stefano. 2023. “Vowel Duration, Voicing Duration, and Vowel Height: Acoustic and Articulatory Data from Italian.” OSF. July 13. doi:10.17605/OSF.IO/XDGFZ.

This contains audio and EGG recordings with Praat annotation. So it's not technically a "description of the phonology" of Italian. In other words, I think it would be helpful to differentiate between a piece of prose that describes a level of grammar from data that can be used to describe grammar or a level thereof.

Ideally the Coretta example could be tagged with "data, phonology" but "data" would flag that it's a data repository rather than a piece of prose.

This aligns nicely with the principles in https://www.degruyter.com/document/doi/10.1515/ling-2017-0032/html

**Comment by d97hah** [comment]
These entries are not in Glottolog (precisely because Glottolog so far is a
bibliography and not a repo of primary data). You are thus suggesting
Glottolog should extend its scope rather than to recategorize entries
already in Glottolog within its narrow. I am not sure this is the right
division of labour as there are other archives with raw data and OLAC
searches them. But your suggestion is noted. all the best, H

Pada Sab, 23 Des 2023 pukul 15.29 Stefano Coretta ***@***.***>
menulis:

**Comment by stefanocoretta** [comment]
That is not quite what I had in mind. :) I think it is the scope of Glottolog to list resources on languages. I don't think "resources" is intended as "prose publication" only, since some entries of resources on glottolog are in fact citations of data repositories.

Those reference entries are not marked with a specific document type. I think it would be beneficial to add a document type "data" so that those (and new entries) could be tagged accordingly.

I am not suggesting Glottolog should be a data repository (there are other services for that).

As an example of some existing references that are data sets:

- https://glottolog.org/resource/reference/id/578437
- https://glottolog.org/resource/reference/id/158989
- https://glottolog.org/resource/reference/id/648852

And there are others.

**Comment by d97hah** [comment]
Afaik those examples *are* publications, not raw data like video, audio
etc. OLAC already does what you are suggesting
http://www.language-archives.org/ what's wrong with it? What would be
better if Glottolog started doing the same?

Pada Sab, 23 Des 2023 pukul 17.25 Stefano Coretta ***@***.***>
menulis:

**Comment by stefanocoretta** [comment]
Those I listed seem to be citations of data sets, for example https://glottolog.org/resource/reference/id/578437 is a citation of the Zenodo entry: https://zenodo.org/records/1689909

Clearly not a "prose" publication. :)

As for OLAC, I don't like it because:

1. It uses the ISO codes instead of the glottolog codes.
2. It only supports specific repositories and it has very specific metadata requirements for a repo to be included. Data stored in repositories that are not the ones harvested by OLAC cannot be discovered there.
3. It lists individual "objects" as individual resources, while for most research purposes, listing the main collection would be more practical.
4. It is affiliated with SIL.

Assume someone curates a set of recordings of an under-documented/described language. The data set is stored on an institutional repository and it gets its own DOI and citation. The resource is added to the relevant Glottolog entry.

When researchers look for resources of that Glottolog entry, they can discover the existence of the data set.

Furthermore, "Text" is already a document type: "some amount of unanalyzed text data ~ 10 pages and beyond". So why having a document type for unanlysed text (which is "data") but not one for audio/video recordings for example?

This is why I think it is a good idea having at least a document type that works for data sets. :)

**Comment by xrotwang** [comment]
@stefanocoretta I agree that such a curated list of data resources would be very useful and that OLAC falls somewhat short of providing it. I think, though, that doing better than OLAC in this respect is out of scope for Glottolog. It would require more effort to be done well than the current Glottolog setup can deal with. Incidentally, we are looking into applying for funding to actually put together such a well curated catalog of language resources. In the meantime, we might start tagging items in Glottolog's bibliography to help us explore this idea, but I don't think a document type - which would be somewhat orthogonal to the other document types which are geared towards computing "descriptive status" of a language - would be really useful.

**Comment by stefanocoretta** [comment]
@xrotwang Thanks, Robert. :) I wonder if it's just a matter of what "descriptive status" means. As of now, the doc type `Text` is clearly not an instance of "description" since the definition states it is "un-analysed" text.

How does this document type "Text" interact with the computation of the "descriptive status"? Which descriptive status would a languoid with just one entry of type "Text" get? How would this be different from a languoid with just one entry of type, for example, "Audio/Video recordings" or something like that?

Related to this, why privileging "text" documentation by having a "Text" type, when in fact most documentation starts with audio/video recordings?

Happy to see you are looking for funding for a curated catalog of language resources. I actually started prototyping something like that some time back, but I just recently realised that Glottolog already has the right scaffolding for that and I thought avoiding separation/reduplication of scopes would be best.

Is there any way I can argue that Glottolog could function as a hub for language resources (both documentary and descriptive, considering some of the references entries are already just "data")? :)

**Comment by d97hah** [comment]
We have a bit of a moving target here. Glottolog traditionally
collects references to publications. Traditionally publications were
always text or printed photos. Publication can be prose or data,
usually both. Descriptive status is a measure of (traditional)
grammatical description and "unanalyzed" text in that context means
not grammatically analyzed. It does not mean unanalyzed primary raw
data since wrt to text, someone wrote it down, which requires some
analysis. Traditionally all grammatical analysis went through such a
step, so that's why it is privileged. Adding a new type 'raw data'
would be orthogonal since the existing categories differentiate the
kind of information included, not its depth of analysis. One could
fit raw audio/video/datasets in the existing scheme depending on what
it is (Swadesh list, dictionaries, stories etc). I don't think
including just any raw data in Glottolog makes scientific sense, only
if the sort of metadata you expect to find in a (scientific)
publication or well-curated repo (e.g., year, place, method etc) is
attached. For just any data you already have archive.org or youtube
for that matter, and for raw data with extensive metadata there is OLAC.
Maybe it's not ideal that you can't add individual items directly
to OLAC, or its a sensible way of controlling for proper metadata
(I don't know). Nothing (I believe) prevents anyone from re-doing OLAC
or adding a layer ontop which aggregates, is not affiliated with SIL,
and uses glottocodes. all the best, H

Pada Min, 24 Des 2023 pukul 10.56 Stefano Coretta ***@***.***>
menulis:

**Comment by stefanocoretta** [comment]
Thank you, Harald. :) Since I see there is no interest in developing this, I will close the issue.

Greetings from Edinburgh!
