### ISSUE TITLE
dialect of waim1255

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#1054]
Can we please have a dialect languoid for "Western Waimaha" that is under waim1255. This is based on Jurriaan Wiegertjes fieldwork and Randall Q. Huber and Robert B. Reed. 1992. Vocabulario Comparativo: Palabras Selectas de Lenguas Indígenas de Colombia. In  Huber, Randall Q. and Robert B. Reed (eds.) Santafé de Bogotá: ILV. xxxvi+387pp.

Please and thank you.

**Comment by d97hah** [comment]
What is  "Western Waimaha"? I can't find anything on Wiegertjes fieldwork
by googling and also not in Huber & Reed 1992

Pada Sel, 20 Feb 2024 pukul 16.10 Hedvig Skirgård ***@***.***>
menulis:

**Comment by JurriaanWie** [comment]
This is about the difference between what has been called Bará (Eastern) and Waimaha/Waimaja (Western) before. Quoting from a paper that I'm working on right now: "Vaímajã can be divided into at least two dialects: a Western dialect, spoken along the Yapú river, and  the Pirá river and its tributary Caño Colorado; and a Eastern dialect spoken along the Tiquié river and its tributaries, as well as the Inambú river. Mutual intelligibility between these two dialects needs to be investigated further, but several speakers report that it is limited. Huber and Reed (1992: xxiii) note “a significant number of lexical differences” between Western and Eastern Vaímajã. [...] Both dialects boast a number of varieties which differ between villages and display varying degrees of similarities in domains of phonology, morphology, syntax, and lexicon."

The reason that I'm doing away with the term Bará and am calling both Vaímajã is because: "Huber and Reed (1992: xxiii) mention that the Eastern clans call themselves Bará and that the Western clans prefer Vaímajã, whereas Stolte and Stolte (1976: 84) make no such distinction, mentioning that “the indigenous people themselves do not like the name Bará, because it may have negative or derogatory connotations” (my translation). In my own experience, the term Bará is used mostly in Spanish and not very much in the Vaímajã language itself. It is used by the Western clans to denote the Eastern clans, as opposed to Vaímajã by which the Western clans refer to themselves. The Eastern clans use the terms Bará and Vaímajã interchangeably, seemingly without a strong negative association with the term Bará. Nevertheless, it appears that all clans have a preference for the term Vaímajã over Bará" therefore, I'm using Vaímajã for both dialects. Glottolog lists Pamoa Bará and Eastern Waimaha right now, which seem to refer to varieties of Bará (i.e. what I'm calling Eastern Vaímajã), whereas Western Vaímajã (i.e. what has been called Waimaha) is not listed as a dialect. Stolte and Stolte use the term Northern Barasano for Vaímajã (eastern and western alike).

Whether it is appropriate to treat these varieties as dialects or languages remains to be seen. As mentioned, there are differences in phonology, morphology, syntax, and lexicon, but they do not seem to be very drastic (e.g. Western Vaímajã does not allow PRO-drop whereas PRO-drop is preferred in Eastern Vaímajã). Multiple people have reported limited mutual intelligibility between Eastern and Western Vaímajã, but according to emic ontology they are the same language, and there is much debate about which dialect is the "correct" one, and which group belongs to the older lineage.

**Comment by d97hah** [comment]
Thanks I'll add W Waimaha (it will be west3014) in this PR
https://github.com/glottolog/glottolog/pull/1055

Do you by any chance have a pdf of this?
Jackson, Jean E. 1973. Marriage and linguistic identity among the Bará
Indians of the Vaupés, Colombia. Ph.D. diss., Stanford University.
xii+299p

Pada Sel, 20 Feb 2024 pukul 17.56 JurriaanWie ***@***.***>
menulis:

**Comment by JurriaanWie** [comment]
Thank you! Sadly, I don't have it...
