### ISSUE TITLE
Sign language updates (LSH[no_code] and BISL[fren1280])

### ISSUE THREAD

**Issue by borstell** [glottolog/glottolog#420]
I've been informed of some possible updates to the sign language documentation:

1. Add _Haitian Sign Language_ (LSH) (a.k.a. _Langue des Signes Haïtienne_), preferably under the [ASLic [asli1244]](https://glottolog.org/resource/languoid/id/asli1244) branch. If added, coordinates could use Port-au-Prince as reference point, as the paper states it as the main hub of the Deaf community `(18.533333, -72.333333)`. Reference below. According to this reference, [American Sign Language [amer1248]](https://glottolog.org/resource/languoid/id/amer1248) could also add "Haiti" to its "Countries" list.
```
@article{hochgesang2016,
	title = {{An Initial Description of the Deaf Community in Haiti and Haitian Sign Language (LSH)}},
	volume = {16},
	issn = {1533-6263},
	url = {https://muse.jhu.edu/content/crossref/journals/sign_language_studies/v016/16.2.hochgesang.html},
	doi = {10.1353/sls.2016.0003},
	language = {en},
	number = {2},
	journal = {Sign Language Studies},
	author = {Hochgesang, Julie A. and McAuliff, Kate},
	year = {2016},
	pages = {227--294}
}
```

2. The preferred name for [French Harbour Sign Language [fren1280]](https://glottolog.org/resource/languoid/id/fren1280) appears to be "Bay Islands Sign Language (BISL)". See [this project entry](https://elar.soas.ac.uk/Collection/MPI1089252) and the reference below.
```
@incollection{Ali2020,
	address = {Berlin/Boston, MA},
	title = {{Bay Islands Sign Language: A Sociolinguistic Sketch}},
	booktitle = {{Emerging Sign Languages of the Americas}},
	publisher = {De Gruyter Mouton},
	author = {Ali, Kristian and Braithwaite, Ben},
	series = {Sign Language Typology [SLT]},
	volume = {9},
	editor = {Le Guen, Olivier and Safar, Josefina and Coppola, Marie},
	year = {Forthcoming}
}
```

3. [Australian Aborigines Sign Language [aust1253]](https://glottolog.org/resource/languoid/id/aust1253) may benefit from being subcategorized, and the status of [Far North Queensland Indigenous Sign Language [fnqi1234]](https://glottolog.org/resource/languoid/id/fnqi1234) is apparently questioned (cf. [this tweet](https://twitter.com/AdamCSchembri/status/1180456844680220672)).

4. The existence of [Old Kentish Sign Language [oldk1238]](https://glottolog.org/resource/languoid/id/oldk1238) is apparently questioned altogether (cf. [this tweet](https://twitter.com/AdamCSchembri/status/1180457897920274432)).

**Comment by d97hah** [comment]
1. Thanks, yes, it is not seem like LSH is assertably unintelligible to
ASL but the opposite is not assertable either, so I'll add it.

2. Ok I'll change the name, hoping the publication in question will be
available soon.

3. It's clear since Kendon's works that Australian Aborigines Sign Language
[aust1253] needs to be split up. But into exactly what? I've never succeeded
in getting an answer to that from people who might know. Do you or do you
know
anyone who would venture to say something concrete on this point? The
questioning of Far North Queensland Indigenous Sign Language in the tweet
referred to is useless since it is not explained why.

4. The questioning in the tweet of OKS is clearly exaggerated, there
is some limited evidence, the questions is whether it is convincing. I
don't have the Jackson 2001 book and the tweet does not explain why that
which exists is not convincing. Can you help here?


Pada tanggal Jum, 11 Okt 2019 pukul 12.23 Carl Börstell <
notifications@github.com> menulis:

**Comment by borstell** [comment]
Thanks!

Yes, I understand that the issues regarding 3 and 4 were very vague. I am not at all an expert in any of these languages but hoped to engage others who are by raising the question on their behalf, with the intention of having more sign language linguists actively participating in the continued development and improvement of Glottolog.

**Comment by d97hah** [comment]
Can these scientists not write more explicit emails as opposed to tweets in
their engagement?

Pada tanggal Sen, 14 Okt 2019 pukul 13.15 Carl Börstell <
notifications@github.com> menulis:
