### ISSUE TITLE
AES based on dialects problems

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#426]
There are 17 languages that have a pop of over 20,000 in e20 but aes in glottolog of "extinct" or "nearly extinct". I understand that Russian is already being dealt with, but Kannada should probably also be changed and possibly some of the others as well. I'm not saying all of these are suspect, but they're probably worth a second look.

It seems to me that this problem stems from assigning aes of languages based on aes statuses of dialects. Can some sort of extra check be done whenever the only available aes of a subdialect is of a certain severity level? Or some other solution?

Is the plan to manually adjust aes scores when errors are pointed out, or to continue the dynamic pipeline from Unesco world atlas, egdis etc but adjust the scripts that render the scores?

Language_ID             Name            aes Population Numeric
1     bang1365           Bangka nearly extinct             340000
2     haio1238          Hai//om        extinct              46000
3     hass1238       Hassaniyya nearly extinct            3763900
4     jadg1238          Jadgali nearly extinct              25600
5     kara1483       Karamojong        extinct             666000
6     komi1268      Komi-Zyrian nearly extinct             156000
7     maka1305   Makassar Malay        extinct            1880000
8     mann1245       Manna-Dora nearly extinct              30000
9     masa1300            Masai        extinct            1455000
10    ninz1246            Ninzo nearly extinct              35000
11    nucl1305          Kannada nearly extinct           37739040
12    peng1244            Pengo nearly extinct             350000
13    russ1263          Russian nearly extinct          153612510
14    sher1258          Sherbro        extinct             178000
15    tata1255            Tatar nearly extinct            5188710
16    tumu1242 Tumulung Sisaala nearly extinct             105000
17    uigh1240           Uighur nearly extinct           10399460

**Comment by d97hah** [comment]
Thanks Hedvig,
These cases are indeed quite ugly and I should have done something
more systematic to rid them. This list is very useful. In the
Bangka case, I think the AES is correct -- the population is
the census figure for the population of the island. For Jadgali
UNESCO seem to be wrong, alt. there is a language confusion case.
Manne-Dore is probably a spurious language. All we have are the
Indian anthropological account which say they speak Telugu, plainly,
not remnants of/ceasing to transmit another language or dialect.
So while there are no speakers now of a Manne-Dora dialect/language,
it is not assertable that there was one which has become extinct.
No information with more linguistic detail has been forthcoming for
a while so it's time we take away its language status (I'll fix).
In the case of Ninzo it seems ElCat is just wrong, the same with
Pengo for UNESCO. A typo in the ISO-code in UNESCO accounts for the
Sisaala case (sil instead of the intended sii for Shompen). The
remaining cases are indeed correct underlying data for a dialect
where the remaining dialects are much safer and thus missing from
ElCat/UNESCO. I've fixed all for next version (in Glottolog, the
import scripts won't be used again).


Pada tanggal Jum, 18 Okt 2019 pukul 07.24 Hedvig Skirgård <
notifications@github.com> menulis:

**Comment by d97hah** [comment]
Oh and Re Makassar Malay I am waiting to obtain some better sources

Pada tanggal Sab, 19 Okt 2019 pukul 15.20 Harald Hammarström <
harald.hammarstrom@gmail.com> menulis:

**Comment by HedvigS** [comment]
Ok, thanks!

If the AES from now on will be manually edited rather than dynamically derived, can there be an explanation of the scale and the levels [here?](https://glottolog.org/glottolog/glottologinformation)

**Comment by bambooforest** [comment]
@d97hah - we also just came across this for Russian (nearly extinct) and Modern Greek (or its dialects) as moribund. It took me a while to find out what AES status is -- after searching the web (nothing relevant popped up there), I went to submit an issue, then found this one, then ended up on the Glottoscope page by accident. Perhaps it's also good to mention it (or at least link to it) on these pages:

https://glottolog.org/glottolog/glottologinformation

https://glottolog.org/about

For the latter, it might be better titled "Credits" in the navigation tab?

**Comment by d97hah** [comment]
Thanks Steve! We've fixed the bulk of these erroneous dialect derived AES
statuses for next version. @Robert maybe time for 4.1 to get them through,
I've gotten a handful of emails about them.

I agree AES should be described in the Glottolog information rather than
just GlottoScope. I've made a PR in glottolog3, @Robert may need to fix it.

Pada tanggal Rab, 6 Nov 2019 pukul 11.36 Steven Moran <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
Will try to push 4.1 out by end of November.

d97hah <notifications@github.com> schrieb am Mi., 6. Nov. 2019, 15:05:

**Comment by HedvigS** [comment]
> Ok, thanks!
> 
> If the AES from now on will be manually edited rather than dynamically derived, can there be an explanation of the scale and the levels [here?](https://glottolog.org/glottolog/glottologinformation)

will aes be manually maintained by glottolog-editors or continually aggregated? I noticed this PR #665 which suggests that data is being imported again.

**Comment by xrotwang** [comment]
We might semi-automatically compare with ElCat or Ethnologue if these are updated. So I'd say it's a process of computer-aided curation. There have been talks about consolidating endangerment assessment from ElCat  and Glottolog in one place. But this process has not really started yet.

**Comment by HedvigS** [comment]
Right, I see. Thanks @xrotwang 
And, will requests about changes unrelated to comparison with the underlying sources for the aggregation be considered?

**Comment by xrotwang** [comment]
Yes. We already had a couple of these, correct @d97hah ?

**Comment by d97hah** [comment]
I'm not sure I understand the question. The best way is still to tell ElCat
to change and then AES will import it in the future.

Pada tanggal Kam, 15 Jul 2021 pukul 09.36 Robert Forkel <
***@***.***> menulis:

**Comment by HedvigS** [comment]
I'm asking if the AES besides being an aggregate now also contain differences that have been introduced by you, and not by the underlying sources. If so, it seems it's no longer purely an aggregate.

**Comment by xrotwang** [comment]
Glottolog is an AES source itself:
https://github.com/glottolog/glottolog/blob/f6531fcec3f4fc36c77f59c66300aac97778540c/config/aes_sources.ini#L5

**Comment by HedvigS** [comment]
> Glottolog is an AES source itself:
> 
> https://github.com/glottolog/glottolog/blob/f6531fcec3f4fc36c77f59c66300aac97778540c/config/aes_sources.ini#L5

Riiight. Okay, interesting ^^!

**Comment by HedvigS** [comment]
Could that be added [here](https://glottolog.org/glottolog/glottologinformation#agglomeratedendangermentstatusaes)?

**Comment by xrotwang** [comment]
yes. https://github.com/clld/glottolog3/issues/136

**Comment by HedvigS** [comment]
Thanks!
