### ISSUE TITLE
Mislinked References on Glottolog

### ISSUE THREAD

**Issue by judithvoss** [glottolog/glottolog#427]
Hey, 

I am coding several Dravidian languages for Grambank right now and work on the description of the Munda language Gutob for my PhD dissertation. While looking for references on Glottolog, I noticed two wrongly linked references:

Under the node for Gutob (Bodo Gadaba in Glottolog, ISO gbj, glottocode bodo1267) Bhaskarao's (1998) Grammar Sketch "Gadaba" is listed. This actually belongs to the unrelated Dravidian language Ollari Gadaba (Iso gdb, glottocode pott1240) (it's listed there, too).

Also under the node for Irula (iru/irul1243), Gail Coelho's grammar of Betta Kurumba is wrongly listed. 

Best regards
Judith

**Comment by d97hah** [comment]
@Robert: This is a q for you since these entries in question are correctly
tagged in the .bibtex. Possibly old associations persist and/or
associations are being made before merging different entries from different
bibliographies.

Pada tanggal Jum, 18 Okt 2019 pukul 14.03 judithvoss <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
As @d97hah says, the bad link is already gone here https://github.com/glottolog/glottolog/blob/86afef2d1df12042a7f5c13534f9d92e3b069ebe/languoids/tree/aust1305/mund1335/sout3137/guto1244/bodo1267/md.ini#L20-L28 so will be gone in the web app after the next release.
