### ISSUE TITLE
Mixtec (mixt1427) bibliography errors

### ISSUE THREAD

**Issue by SAuderset** [glottolog/glottolog#431]
I went through all the bibliography entries on Mixtec languages (for thesis stuff) and noticed a few errors, which I'll list below. Mostly it concerns Zapotec and Chatino references wrongly assigned to Mixtec.
Thanks so much for continuously improving Glottolog! 

**assigned wrong:**
- Mitla Zapotec grammar => should be assigned to mitl1236
- Belmar, Francisco. 1902. Dialectos. In Investigaciones sobre la lengua Chatina, 12-19. Oaxaca: Imprenta del Comercio => Chatino (not sure which exact variety)
- Ishihama Juntaro. 1956. Seikago yaku Ro Keikyo KoKyoden. Bunka 20. 865-9. => this is something Sino-Tibetan
- López, Gregorio M. 1958. To bzin= gozeb dao= len jempl che to conejw na= to beza= (El ratoncito huerfanito y cuento de un conejo y un zorro). Instituto Lingüístico de Verano. 28pp => this is Zapotec
- Instituto Lingüístico de Verano. 1960. Tu betsi nna tu bedina (El león y el ratón; El conejo y el lobo). Instituto Lingüístico de Verano. 8pp. => Zapotec
- Rendón, Juan José. 1971. Relaciones externas del llamado idioma papabuco. Anales de Antropología 8. 213-231. => about Zapotec, according to my knowledge about zani1235
- Instituto Lingüístico de Verano. 1976. Ca=a enta tucu cuentu bicha cona bichuú cona xíbiti (Un cuento del conejo, coyote y zorrillo). Instituto Lingüístico de Verano. 4pp. => Zapotec
- Ndyacu coyote romsaa lo=o conejo (El coyote almuerza con el conejo) => Chatino
- Zurita, Estéban. 1978. Chop cuent chen conef (El conejo mañoso). Instituto Lingüístico de Verano. 24pp => Zapotec
- Cuent que conecw len yeto be=eze (Cuento del conejo y la zorra) => probably Zapotec
- Shcuent to conejü noo to deqy (El cuento del conejo y el sapo) => Zapotec
- Xcuent to conejü no to mban (El cuento del conejo y el lagarto) => Zapotec
- Xcuenta cuneju bueu cun dxídxingula (El cuento de un conejo y un coyote) => Zapotec
- Ni guhc deqy leññ cuev no to conejü (Lo que sucedió en la cueva a un sapo y un conejo) => Zapotec
- Cuentu gue nanto beo len taatubiisa, beaca ta cuneejuna loo nanto beo na => Zapotec
- Xcuent coneju ni bziib to xan buiahl[;] El cuento del conejo que sembró un grano de maíz => Zapotec

In addition, some entries are tagged wrong or have some other errors:
- Pike, Kenneth L. 1949. A Problem in Morphology-Syntax Division. Acta Linguistica. 5 => the year is 1945 and this is not a grammar, it's on a specific topic
- North, Joanne and Jäna Shields. 1978. Gramática Popular del Mixteco: Mixteco de Silacayoapan. Mexico: Summer Institute of Linguistics. => grammar sketch, not grammar (it's only 45 pages long)
- Hills, Robert A. and Eunice V. Pike. 1967. Phonology and Morphotonemics of Ayutla Mixtec. International journal of American linguistics 33. 287-299. => duplicate entry with wrong author (right record is already listed)
- Hinojosa H., Francisco. 1977. Mixteco de Santa María Penoles, Oaxaca. Archivo de Lenguas Indígenas de México. => duplicate entry, Hinojosa was the editor, not the author
- Daly, John and Margarita Holland de Daly. 1977. Mixtec de Peñoles. Archivo de Lenguas Indígenas de México. México, D.F.: Centro para la Integración Social.=> duplicate entry

**Comment by d97hah** [comment]
Thanks Sandra,
I fixed all things for the next version except:

* Rendón, Juan José. 1971. Relaciones externas del llamado idioma papabuco.
Anales de Antropología 8. 213-231. => about Zapotec, according to my
knowledge about zani1235

According to my notes this contains:

10 variantes del zapoteco: Elotepec [zte], Elotepec según Belmar ("1901
papabuco") = Zapotec-Elotepec [zte], Recibimiento de Cuauhtémoc =
Mixtec-Cuyamecalco [xtu], San Felipe Tejalápam = Zapotec-Tejalapan [ztt],
Zaachila = Zapotec-Zaachila [ztx], Santa Lucia Ocotlán = Ocotlán Zapotec
[zac], Coatecas Altas = Coatecas Altas Zapotec [zca], Santa Maria Coatlán
[zps], San Agustín Loxicha y Cuixtla = Zapotec-San Baltazar Loxicha [zpx]

Which one is zani1235?

* Pike, Kenneth L. 1949. A Problem in Morphology-Syntax Division. Acta
Linguistica. 5 => the year is 1945 and this is not a grammar, it's on a
specific topic

The years seems to be 1949 since citations agree it's 1949 on this and
other articles in the same issue (T&F website is wrong here)



Pada tanggal Kam, 31 Okt 2019 pukul 12.41 Sandra <notifications@github.com>
menulis:

**Comment by SAuderset** [comment]
Cool, thanks so much!

Re Rendón: I'm really not an expert on this, so if it says there are 10 variants of Zapotec represented that is probably true. zani1235 would be zpw.

Re Pike: Oh, yes, I see now why the confusion arises. OLAC lists it as 1949, but when you look up the paper on Acta Linguistica it says 1945 (https://www.tandfonline.com/doi/abs/10.1080/03740463.1945.10410896) and that was where I looked it up. So I'm not sure which one you want to go with.
