### ISSUE TITLE
N'ko [nqo] now "retired, bookkeeping" ???

### ISSUE THREAD

**Issue by verdy-p** [glottolog/glottolog#568]
The recent submission incorrectly assumes that a language which is supposed to be "extinct" (from The Ethnolog update) caused that language to have all its data removed from Glottlog.

This is wrong for this language which is very active, not removed from ISO 639. In fact it has never been so active on the web (thanks to the improved support of its scripts by popular free and open fonts in major OSes including mobile OSes).
There's an active community, there are active contributors.

Even if this is a koiné for a standardized written form for several Mandingue languages, it becomes a separate language by itself (even if it's only written and not spoken in a single form). Other koinés are kept in Glottolog. The only thing that did not emerge was to develop it as an oral language: each separate language keeps its own tradition, its own phonology and their associated orthographies in various scripts, even if all these are unified in a standard form when using the Nko script.

It's much like "Standard Arabic", or "Standard Chinese" (even if for it there are two unified orthographies with Simple or traditional sinograms, or possibly other scripts like Bopomofo, and some historic variants used in Vietnam, Korea, Japan or elsewhere)

Please find a way to restore the links to relevant ISO 639, Wikipedia/Wikidata, because this koiné is definitely not even "extinct" as indicated, and it is even actively taught (may be outside the original area in Western Africa).

The only "misunderstanding" is in Glottolog. It is clear that it should be part of the Mandingue family.

**Comment by d97hah** [comment]
I am not sure which links fail to link to the respective ISO 639. Afaik
there should only be one from Glottolog and it seems to be there. The
definition of extinct in Glottolog is "no L1 speakers" which afaik is the
case here. all the best, H

Pada tanggal Sen, 5 Okt 2020 pukul 18.32 Philippe Verdy <
notifications@github.com> menulis:

**Comment by verdy-p** [comment]
"Which link"? There's NO link at all to any resource for [nqo]. The page on Glottolog just says it is "retired" which it is of course not, and it is gaining in use and popularity, not loosing it, not just across speakers of Mangingue languages in the native region of West Fraica, but also elsewhere. And there are active works publishing online dictionaries that are growing in size, and na increasing usage on the net (including Twitter, and many messaging apps on Android, less on iOS but it is still present because its script is well supported now by these platforms and is also supported in Windows).
May be that language has no L1 speaker, but as a L2 (and an important written koiné) language, it is very active, much more than most languages in Glottolog (including many that are only historic, with very scarce resources and not even spoken or written actively).
And in ISO 639-3 it is standardized accurately as a "living" language, there's no reason to retire from Glottolog any living language.
The message at top is also misleading: "This entry has been retired and is featured here only for bookkeeping purposes. Either the entry has been replaced with one or more more accurate entries or it has been retired because it was based on a misunderstanding to begin with."
"Bookkeeping" is evidently wrong. And there's NO more accurate entries, it has not  been retired for the reason exposed as there's no demonstration at all that it was based on a misunderstanding to begin with. In fact this written koiné is also starting to be spoken by reading it as it is, and mandingue people can understand it. It is also the foundation of a more accurate orthography of the various mandingue languages, badly written with the Latin or Arabic scripts that cause also much more misunderstanding across other written L1 mandingue languages, so it starts becoming a "hat" language, with a status similar to the early stages of modern French or modern English or modern high German, when they started to be regulated by an academic authority creating a written koiné standard before it became the standard form allowing other related languages to coverge and borrow words and forms from each other via the koiné. With the development of mobile networks in Africa and the cost of communications, using this written language on short instant messaging is useful and helps reviving all these languages spoken by millions people spread over a large region.

And anyway you don't provide ANY reference for that language to sustain your claim. But it is really easy to find many references on the net, including active monolingual and bilingual dictionnaries, or the language description in The Ethnologue, ISO 639-3, Wikipedia (which also sites external references), and various lingusitic resources for translators or localizers of apps, or references for font designers (for the script, which is not complicate to support, similar in graphic complexity to Hebrew, but simpler to compose than Hebrew or Arabic and a clear mapping with the essential phonology, even if it is not a pure phonetic transcription: that script can be read according to the phonology of each mandingue language, and many words are relatively easily recognized).

How can you retire a language recognized by millions living people?

**Comment by d97hah** [comment]
Your original rant complained there was no ISO 639-3 link, but there is, in
the usual place at the top right. There are no references tagged to this
language because we're not trying to collect all references for this sort
of entity, but nothing has been removed. The extinct label, as explained,
refers to the number of L1 speakers, not whether the language is used or
not (e.g. Latin is also listed as extinct, but there are radio shows and
what not in Latin). We can move it from retired to Artificial Language if
it makes you happier (the original iso 639-3 entry does not identify it as
such and it thus spurious as an entry representing an L1 language, but
there is not much difference). all the best, H

Pada tanggal Kam, 8 Okt 2020 pukul 22.17 Philippe Verdy <
notifications@github.com> menulis:

**Comment by verdy-p** [comment]
I'm not "ranting" like you think. But the rational is completely illogical:
so why are you retiring N'Ko, but not many historical languages that are no
longer used even at L2, but only read by a few specialists with lots of
uncertainty (e.g. Mycenean Greek, that is not even completely deciphered,
or Old French, Old English, Old Greek that are no longer used at all by
active speakers).
N'Ko is very active and popular even if it is only written. It has active
work on its dictionary, it has printed publications (including in official
libraries, with their ISBN or ISSN) and websites.
And I've absolutely not asked for it to be reclassified as "Artificial"
(which is your pure invention) when this is clearly a distinctive language
of the Mandinge family that should have remained there, just like it is in
ISO 639-3.
I only criticize the decision in Glottlog to retrieve it as "bookkeeping"
and with a complete false statement of the reason, under an inconsistent
reason not stated (being not L1 should mean you should retire all historic
languages that are no longer L1).

**Comment by d97hah** [comment]
Hi! I'll explain once more but that'll be it. The logic is not exactly
difficult. There's good reason to believe Mycenean Greek, Old English
etc were once L1 languages, which is not the case for N'Ko. It is not
the popularity or activity of an entity which determines its status in
Glottolog. You are probably looking at the wrong website relative to
your objectives. If you want a listing of popular registers, active L2
communites etc please look elsewhere than Glottolog (iso 639-3,
wikipedia, books etc). The ISO 639-3 entity [nqo] is in bookkeeping
precisely because some (but not all) of its characteristics as
described there imply an L1 language, yet it is not an L1 language. It
is the N'ko as an L1 language (implied by ISO 639-3) which is
bookkeeping-spurious. Glottolog tries to help people coming with an
ISO 639-3 division to see what their correspondence is in the
Glottolog (L1 language) division. N'ko as a literary register or L2
language, as you note is not spurious/retired or even extinct, so you
might expect to find it in Speech Registers or Artificial languages at
Glottolog, but Glottolog is not really trying to be complete with such
entities, and there are uncountably many entities of this sort
missing, whether popular or unpopular. Perhaps the best we can do for
users like you is to list [nqo] as an Artitifical language, which does
relatively little damage to the logic above. all the best, H

Pada tanggal Sab, 10 Okt 2020 pukul 22.44 Philippe Verdy <
notifications@github.com> menulis:

> I'm not "ranting" like you think. But the rational is completely illogical:
> so why are you retiring N'Ko, but not many historical languages that are no
> longer used even at L2, but only read by a few specialists with lots of
> uncertainty (e.g. Mycenean Greek, that is not even completely deciphered,
> or Old French, Old English, Old Greek that are no longer used at all by
> active speakers).
> N'Ko is very active and popular even if it is only written. It has active
> work on its dictionary, it has printed publications (including in official
> libraries, with their ISBN or ISSN) and websites.
> And I've absolutely not asked for it to be reclassified as "Artificial"
> (which is your pure invention) when this is clearly a distinctive language
> of the Mandinge family that should have remained there, just like it is in
> ISO 639-3.
> I only criticize the decision in Glottlog to retrieve it as "bookkeeping"
> and with a complete false statement of the reason, under an inconsistent
> reason not stated (being not L1 should mean you should retire all historic
> languages that are no longer L1).
>
>
