### ISSUE TITLE
Wrong languoid name: Serres-Sechidou Romani

### ISSUE THREAD

**Issue by ViktorElsik** [glottolog/glottolog#575]
The name of https://glottolog.org/resource/languoid/id/serr1257 contains, by mistake, the name of the author of the description (Sechidou).

**Comment by d97hah** [comment]
Thanks I'll adjust that (it was not really a mistake at the time it was
entered because Matras 2002 simply said "a different dialect in Serres (pc
Sechidou)" as opposed to other Arli-type dialect(s) in Serres).

Pada tanggal Jum, 16 Okt 2020 pukul 00.49 ViktorElsik <
notifications@github.com> menulis:
