### ISSUE TITLE
Classification of Lomavren, Caló, Scandinavian Romani

### ISSUE THREAD

**Issue by ViktorElsik** [glottolog/glottolog#576]
1. The languoid https://glottolog.org/resource/languoid/id/loma1235 is a variety of Armenian (as it has Armenian grammar), not Indo-Aryan (which is only the source of some lexicon).

Similarly:
2. The languoids under https://glottolog.org/resource/languoid/id/calo1236 are varieties of Romance languages (Portuguese in case of Brazilian Calão, Spanish in case of Spanish Caló and Portuguese Calão, Catalonian in case of Catalonian Calo), not Indo-Aryan (only some lexicon and fossilized grammatical morphemes).

3. The languoids under https://glottolog.org/resource/languoid/id/scan1239 are varieties of Swedish and Norwegian, not Indo-Aryan (only some lexicon and fossilized grammatical morphemes).

**Comment by d97hah** [comment]
Hi Viktor! Thanks for your feedback. Yes you are right, the
Para-Romani varieties should not be under Indo-Aryan. I've been slowly
moving them away to be grouped with their matrix language (e.g,
romano-greek, danish romani) but haven't gotten through the cases you
mention. The reluctance is because grouping them as (normal L1)
languages with their matrix language implies that they borrowed a lot
of basic vocabulary from a (dying) Indo-Aryan language. As far as I
understand, this is what actually happened. But L1 languages are not
supposed to borrow basic vocabulary to this extent according to a
widely held principle. Maybe this principle is just wrong in its most
general form, and should be modified for the Romani and
Ma'a/Mbugu-type circumstance. That's a perfectly good alternative but
there's also the possibility that the Para-Romani varieties rather
resemble speech registers (where no borrowing hierarchies are known to
hold). But for, e.g., Swedish Romani, Lindell & Carling 2008 says it
was the "mother tongue" of her main informant, which, if taken
literally, would preclude it from being a speech register. I don't
know about the L1 status of the other Para-Romani varieties and I find
it difficult to believe that the Scandoromani of Carling's main
informant was his mother tongue (he was born 1981 and went to normal
Swedish school). Do you have any thought about these questions? (both
on the factual L1 status of different Para-Romani varieties and
whether this has anything to do with their classification)

Re Iberian Romani I believe an early non-Para-Romani Catalan Romani is
attested
(but I haven't inspected the original paper myself).

Re Norwegian Romani, Elsik & Benisek 2020 cite

Wiedner, Jakob. 2017. Norwegian Romani: A linguistic view on a minority
language
in the north of Europe. PhD thesis. Oslo: University of Oslo.

which I haven't seen but I've just now figured out it appeared under a
different title:

https://bibsys-almaprimo.hosted.exlibrisgroup.com/permalink/f/1bm357c/BIBSYS_ILS71542718920002201

Do you have a PDF copy of it (regardless of the title)?

all the best,
H


Pada tanggal Jum, 16 Okt 2020 pukul 01.00 ViktorElsik <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
@d97hah can this be closed?

**Comment by d97hah** [comment]
Yes, except I forgot to adjust Lomavren, but I'll do that for next version.
all the best, H

Pada tanggal Jum, 14 Mei 2021 pukul 14.31 Robert Forkel <
***@***.***> menulis:
