### ISSUE TITLE
West Polesian glottocode please

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#581]
Kristian Roncero (@roncerok) would like for West Polesian to have its own glottocode separate from Belarusian. Ideally at language level, but even a dialect code would be helpful. 

This concerns these two publications:

- Kristian Roncero Toledo. 2019. A typological approach to West Polesian Morphology and Syntax. (Doctoral dissertation, University of Surrey; 484pp.)
- Kristian Roncero Toledo. 2015. West Polesian Inflectional Morphology: A preliminary approach. (MA thesis, University of the Basque Country).

Kristian will be posting further information about the distinctiveness of West Polesian compared to Belarusian in this thread to motivate singling it out as its own language

**Comment by d97hah** [comment]
Great, I remember reading the phd and decided it was not a separate
language in the MI-sense, but happy to be convinced otherwise, and in any
case add dialectal variants to Belarusian

Pada tanggal Kam, 19 Nov 2020 pukul 13.49 Hedvig Skirgård <
notifications@github.com> menulis:

**Comment by HedvigS** [comment]
Super.

**Comment by roncerok** [comment]
Dear Harald,

I will bring a more detailed case of why I think it should be included as a language. I was very careful of not using that term on my PhD because it would have put me at a very high risk whenever returning to Belarus (the Government was controlling quite strictly everything I was doing). One can argue that the differences between the Eastern Slavic branch are also not big enough to consider them fully distinct languages (particularly between Belarusian and Russian), but again, I'll come again to this topic when I show the evidence. [PLEASE DELETE THIS SECTION IF THIS MESSAGE EVER BECOMES PUBLIC]

In any case, if you would like to include West Polesian as a variety of Belarusian, your Glottolog page would be inaccurate, because you only include three dialects/varieties (North-Eastern; Central and South-Western); however, even the most conservative Belarusian dialectologists would consider that South-western Belarusian and West Polesian are distinct varieties. So perhaps, while you decide whether you would like to include West Polesian as a separate Eastern Slavic language, you could create a new entry/variety on the Belarusian page (although some Ukrainians would also argue why haven't you included it on the page of Ukrainian, but that's a long story.) 

I will be working on a more elaborate report and I will come back to you.

Best,
Kristian

**Comment by HedvigS** [comment]
Have I understood it correctly[ that this commit  774c9e4a5da4f755b2bbb0e5d4be9ae539094c27](https://github.com/glottolog/glottolog/pull/786/commits/774c9e4a5da4f755b2bbb0e5d4be9ae539094c27) creates "west2977" which refers to West Polesian? If so I'm happy for now, and we can close this issue. Kristian and Harald can continue discussing the level status of West Polesian, i.e. if this languoid should be upgraded to language instead of dialect. I'll leave that to them though, I'm happy to have a separate code that we can use in Grambank.

**Comment by roncerok** [comment]
Hi!

Yes, it seems that it refers to West Polesian. Thank you, Hedvig!

I'm happy to provide whichever evidence is needed, though if you need a
wordlist, it will take a bit until I go home for Christmas (I only have a
hard copy of the dictionary at my parent's). Otherwise, happy to share
about the morphology, syntax and main phonological processes distinguishing
West Polesian from the rest of the branch.

Best,
Kristian

Le sam. 4 déc. 2021 à 11:11, Hedvig Skirgård ***@***.***> a
écrit :

**Comment by HedvigS** [comment]
Thanks @roncerok . I think based on the Glottolog language classification principles Harald will indeed be needing basic vocab list. That can happen whenever you have time. In the meantime, I'm very happy that there is a unique glottocode identifying West Polesian, regardless of level. I'll leave you guys to sort out the level amongst yourselves.
