### ISSUE TITLE
missing glottocode for Myanmar Sign Language

### ISSUE THREAD

**Issue by Bibiko** [glottolog/glottolog#703]
ISO-Code: `ysm`

sources:
- https://iso639-3.sil.org/code/ysm
- http://endangeredlanguages.com/lang/10958
- https://en.wikipedia.org/wiki/Burmese_sign_language

**Comment by d97hah** [comment]
Already in repos

Pada tanggal Sel, 20 Apr 2021 pukul 13.02 Hans-Jörg Bibiko <
***@***.***> menulis:

**Comment by Bibiko** [comment]
Oh, sorry, my fault - I looked it up against Glottolog 4.3 and not against the latest repo.

**Comment by Bibiko** [comment]
Is it correct that yang1309 only lists `hid = ysm` but not `iso639-3 = ysm`?

https://github.com/glottolog/glottolog/blob/master/languoids/tree/sign1238/deaf1237/myan1234/yang1309/md.ini#L5

**Comment by d97hah** [comment]
Not correct (the effect you see has to do with the ISO-tables on my
computer at the time I added the language) but this and other potential
cases will be fixed in one go just before every new release. If you need it
fixed now, I can of course fix it now.

Pada tanggal Rab, 21 Apr 2021 pukul 11.53 Hans-Jörg Bibiko <
***@***.***> menulis:

**Comment by Bibiko** [comment]
ah - good to know - no problem, no hurry
