### ISSUE TITLE
Missing glottocode for language 'Nunu' of DR of Congo

### ISSUE THREAD

**Issue by Bibiko** [glottolog/glottolog#731]
• see https://www.researchgate.net/publication/338763920_Untangling_the_West-Coastal_Bantu_Mess_Identification_Geography_and_Phylogeny_of_the_Bantu_B50-80_Languages page 176
• should be related with https://glottolog.org/resource/languoid/id/boma1248 (?)
• similar to Kempee https://glottolog.org/resource/languoid/id/kemp1234 (also known as Mpe, Kimpe)
• due to Lorenzo Maselli (Department of Languages and Cultures. Research group(s), Ghent University, Gent, Belgium) it's spoken between Mushie Territory and Nioki in the Mai-Ndombe Province of the Democratic Republic of the Congo

**Comment by d97hah** [comment]
Hi HJ! I haven't added a separate Glottocode for this doculect since it
still needs to be clarified what it's status is (fisherman sociolect?
dialect of Mpee? Alternate name to Mpee?), something not really answered by
the Pachiarotti paper (or, afaik, other papers). In general if you know the
source of a doculect you can check how it is rendered (whether correctly or
wrongly) in Glottolog by inspecting the corresponding bibtex entry in
hh.bib, e.g., for this Nunu you get

Nunu-Sud closest to Mpee [NOCODE_Kempee]

Nunu B80Nu at Mushie/Zaire 16.9E/3.1S closest (Pacchiarotti 2019:184) to
Mpee [NOCODE_Kempee]

Nunu (Letomo) Nunu B822 B822 B [B80Nu] -3.1 16.9 -3.05 16.87 Letomo (DRC) =
Nunu-Sud closest to Mpee [NOCODE_Kempee]

Pada tanggal Sab, 26 Jun 2021 pukul 11.52 Hans-Jörg Bibiko <
***@***.***> menulis:
