### ISSUE TITLE
teasing out varieties of  lian1255 masi1266?

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#811]
Over in the GB project we've got a bit confused when it comes to some descriptions and what languoids they are referring to. We were wondering if you @d97hah might be able to shed some light?

Here's a summary of discussions between me and coder Daniel.

We want to code lian1255. Glottolog lists a grammar sketch for Liana-Seti in Tauern (1928, 1929, 1930, 1931). In these publications, there is no grammar sketch referring to a language with the name Liana-Seti. However, there are sketches on Uhei-Kahlakim and Liambata ("Liambata-Dialekt der Alfuren von Ostseran - Bonfia-Sprache”). Alternative names for Liana-Seti are i.a. Liambata-Kobi and Uhei Kahlakim. 

Collins (1986:125) mentions that Masiwang (masi1266) has formerly been called “Bonfia”. Possibly, the sketch "Liambata-Dialekt der Alfuren von Ostseran - Bonfia-Sprache” contains masi1266 and the sketch “Dialekt von Uhei-Kahlakim” contains lian1255?

We could ask for Uhei-Kahlakim and Liambata to be dialects of lian1255 and Bonfia under masi1266, but the title "Liambata-Dialekt der Alfuren von Ostseran - Bonfia-Sprache" still confuses.

**Comment by d97hah** [comment]
See https://glottolog.org/resource/reference/id/143037 for my conclusion,
similar to yours. Alternative names are not necessarily unique and I don't
otherwise understand what you are confused over. If something is  wrong on
Glottolog please report it here, otherwise do not use the glottolog-github
forum as your research assistant. all the best, H

Pada tanggal Sen, 31 Jan 2022 pukul 15.12 Hedvig Skirgård <
***@***.***> menulis:

**Comment by HedvigS** [comment]
Ok. I thought that there might have been something wrong in Glottolog but I wasn't sure.
