### ISSUE TITLE
Name change for maza1295 from Mazatecan to Mazatec

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#830]
Shun Nakamoto who is an expert on Popolocan languages says:

_I know of no linguist using "Mazatecan". Thanks to Google Books I've just seen "Mazatecan" in an annotated bibliography of the volume 5 of Handbook of Middle American Indians for Gudschinsky 1953, but Gudschinsky herself uses "Mazatec" instead of "Mazatecan". Terrence Kaufman (2004) uses "Masatecan" with < s > for Popolocan (which Glottolog has as "Popolocan-Mazatecan") but he is the only linguist who uses that term and in another sense._

**Comment by d97hah** [comment]
Mazatec is ambiguous with the conception of Mazatec as a single language
(Brinton, Cowan etc), for this reason Mazatecan is preferable. all the
best, H

Pada tanggal Rab, 30 Mar 2022 pukul 18.52 Hedvig Skirgård <
***@***.***> menulis:

**Comment by HedvigS** [comment]
Shun later wrote:

_And after seeing Glottolog editor's comment on "Mazatecan":
- I don't know details about adjectivization in English but I see no justification as to why "Mazatecan" should be used, because…
a) Despite intelligibility tests, the Mazatec people do have this ideology that Mazatec is a language with dialectal variation, and adult speakers of divergent varieties generally know the prestigious Huautla variety.
b) This situation is similar to that of Japanese, where Glottolog has "Eastern Japanese", "Western Japanese", etc. under "Japanese".
c) This situation is different from that of Zapotec or Mixtec, which are more diversified and more scattered, nevertheless they appear as "Zapotec" or "Mixtec", specifying subgroups by regions and communities.
d) I reiterate that "Mazatecan" itself is already a confusing term because of Kaufman._

**Comment by d97hah** [comment]
Re (a-b) it's the intelligibility tests that matter and I don't think the
situation is akin to Japanese. Re (c) the groups Zapotecan and Mixtecan
do occur with those names in Glottolog (though there is a group Zapotec
too, but in this case it's because Zapotecan is already busy and this
is accordance with the literatue). The forms without -an for specific
regions and communities is desired behaviour. Re (d) as you note, his
term was Masatecan and he was the only one to use it in this other sense.
Would Mazatecic be better?


Pada tanggal Kam, 1 Sep 2022 pukul 07.10 Hedvig Skirgård <
***@***.***> menulis:
