### ISSUE TITLE
Another dialect code under gura1251?

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#834]
Mahmoudveysi (2012) describes a dialect spoken in the village Gawraju, which is 10 kilometers from Gawhara which has a dialect glottocode (gawh1238). Would it be possible to have a separate glottocode for the variety spoken in Gawraju? Just to be as faithful as possible to the source material.

**Comment by d97hah** [comment]
Gawhara is a historical center for the community documented at Gawraju,
it's meant to cover Gawraju, not just Gawhara. So you probably want to use
the Gawhara code rather than add separate codes for every village. all the
best, H

Pada tanggal Sen, 4 Apr 2022 pukul 10.13 Hedvig Skirgård <
***@***.***> menulis:

**Comment by HedvigS** [comment]
Okay, thanks
