### ISSUE TITLE
popolocan tree details

### ISSUE THREAD

**Issue by HedvigS** [glottolog/glottolog#884]
Shun Nakamoto writes:

 _the first separation of Mazatec from the other two subgroups of Popolocan (i.e. Ixcatec and Chocho(ltec)-Popoloca) has been presupposed in almost all Popolocan literature, but no published study has demonstrated shared innovation b/w Ixcatec and Mazatec, b/w Ixcatec and Chocho(ltec)-Popoloca, or b/w Mazatec and Chocho(ltec)-Popoloca.
- even though we suppose that Mazatec separated first, "Ixcatec-Chocho-Popolocan" is inadequate, because Ixcatec should be coordinated to Chocho(ltec)-Popoloca (see Hamp 1958; 1960; see also the following lines)
- concerning Chocho(ltec)-Popoloca, there are various points to consider:
- 1. as is already reflected in Glottolog, they form a subgroup (Hamp 1958, 1960).
- 2. exonym/endonym question is a bit tricky, because they share the endonym Ngiwa (or its orthographical variants)* and the division of exonym is a 19th-20th century thing (see Swanton 2016: §1.2 for a complete picture); there have been proposals from communities as well as academic works to use Ngiwa for both Chocho(ltec) and Popoloca (cf. preface of Domínguez Medel and Aguilar Domínguez 1997) and I'm with that opinion.
- 3. the majority of classifications have presupposed the separation between Chocho(ltec) and Popoloca (and genetic unity of Popoloca varieties/languages); however, no published study has demonstrated shared innovations among Popoloca varieties (though I'm aware of a few); in fact, Kaufman (2004) put it in doubt and coordinated three Popoloca varieties together with Chocho(ltec) on the same level.
- Glottolog's = E. Campbell's (2017) subclassification of Popoloca varieties seems to be an unreasoned projection of "Northern", "Western" and "Eastern" used in SIL publications in the 60s-80s for Tlacoyalco, Otlaltepec and Atzingo applied over 7 languages according to their mutual intelligibility tests, and is not based on structural consideration. By the way, I argued in my BA thesis (2016, §2.4) that hitherto Western and Eastern Popoloca share a series of morphological innovations by substituting 1st person plural inclusive stem alternations with 3rd person stem form and an enclitic =ni, and called it "Southwestern Popoloca". As far as I know, Temalacayuca and Tlacoyalco have some lexical isoglosses in common but no shared innovations._

**Comment by HedvigS** [comment]
Also: 

_- Glottolog cites Kirk (1966) and Léonard et al. (2012), but neither of them provides a genetic classification. Kirk (1966) reconstructed Proto-Mazatec picking up apparently conservative features of descendant languages/varieties but he didn't propose ramifications of them, and Léonard (2012) is a sociolinguistic/geolinguistic interpretation of second-hand data from Kirk (1966), but their classification is not based on shared structural innovations. As far as I know, the only published structural/genetic classification of Mazatec varieties is Gudschinsky, Sarah. 1958a. Mazatec dialect history: A study in miniature. IJAL 34(4) 469-481. I know of Michael Swanton's 2013 presentation cited in E. Campbell (2017) but I don't have his handout (I should ask him for that). I also made a few comments in Nakamoto (2020: §10.2) arguing that Ayautla should be grouped together with Soyaltepec and Ixcatlán according to some shared innovations._

**Comment by d97hah** [comment]
* 'even though we suppose that Mazatec separated first,
"Ixcatec-Chocho-Popolocan" is inadequate, because Ixcatec should be
coordinated to Chocho(ltec)-Popoloca (see Hamp 1958; 1960; see also the
following lines)'

I don't get the "inadequacy", the current Glottolog tree is as suggested and
there is no rule that names like "Ixcatec-Chocho-Popolocan" should be read
as
tripartite.

* Re the grouping of Popolocan vs Chocho: I don't know what Kaufman (2004)
is but Kaufman (2006) and references therein do not contain an argument for
his view either (and continue the N, E, W division of Popolocan). I was
unaware of the arguments in Nakamoto (2016) --- I don't have access to this
--- but I see now there's a handout where you give the new internal
classification of Popolocan which I'll follow for next version of Glottolog.
It does contain the Popolocan node and you say here you know some
innovations
so that will do for the time being.

* Re Mazatec internal clf: That of Gudschinsky has its shortcomings
(and is incomplete) as noted in Nakamoto 2020:10-12. Léonard
(2012:20-21) does give a *classification* rather than a
socio/geolinguistic interpretation based on 31 phonological features
(the examples given are innovations) but, indeed, it's incompletely
explained how the clf is derived exactly. I've adjusted it for next
version of Glottolog based on a closer reading of Gudschinsky,
Nakamoto 2020, Leonard 2012, 2017.


Pada tanggal Kam, 1 Sep 2022 pukul 07.17 Hedvig Skirgård <
***@***.***> menulis:
