### ISSUE TITLE
Best practice to add an entry to bibliography?

### ISSUE THREAD

**Issue by martino-vic** [glottolog/glottolog#928]
I wanted to suggest adding a certain source to the bibliography via a pull request but couldn't find any best practice guidelines how to go about. I imagine there are many options, like one could add a bibtex-key directly to one of the .bib files, such as [mpieva.bib](https://github.com/martino-vic/glottolog/blob/master/references/bibtex/mpieva.bib), or add it to one of the primary sources, such as [evobib.bib](https://github.com/lingpy/evobib/blob/master/evobib.bib), or create a new .bib file. Or should one rather just open an issue and ask to add the source? Thank you in advance for the help! And sorry in case I overlooked the location of the guidelines, I just checked the glottolog website and the readme.

**Comment by d97hah** [comment]
If you just want a source added, then yes just open an issue. If you want
to add to a separate named biblio because you are adding a substantial
present or future amount of references then do a PR with the new biblio.
Don't do PRs adding to existing biblio:s unless they are
corrections/well-founded additions to that specific biblio. I.e., if you
know there's a book at the MPIEVA library that's not there in mpieva.bib,
then add there, otherwise not.


Pada tanggal Sen, 13 Feb 2023 pukul 19.51 Viktor Martinović <
***@***.***> menulis:

**Comment by martino-vic** [comment]
Perfect, thank you so much for clarifying!
