### ISSUE TITLE
Replace Rengasdengklok with Cikarang

### ISSUE THREAD

**Issue by JoeMustafa73** [glottolog/glottolog#935]
Replace the Betawi Rengasdengklok dialect with Cikarang, because the Rengasdengklok people speak Sundanese, while the area closest to Cikarang is a Betawi speaker.

**Comment by d97hah** [comment]
Rengasdengklok was likely Betawi speaking in the past (see the maps at the
end of Grijns 1991) but it makes sense to rename it Cikarang anyway since
that it a more viable form of presumably the same dialect.

In the future, please read the extant sources in Glottolog and provide
sources for your suggested changes.


Pada tanggal Sab, 18 Feb 2023 pukul 18.45 JoeMustafa73 <
***@***.***> menulis:

**Comment by JoeMustafa73** [comment]
Untuk dialek Cikarang saya merujuk pada rujukan ini.

https://www.researchgate.net/publication/345401916_Dialek_Betawi_Jakarta
